sudo: required
dist: centos
language: go

go:
  - 1.10.3
  - 1.9.7

env:
  global:
    - TEST_ZABBIX_URL=http://localhost:80/zabbix/api_jsonrpc.php
    - TEST_ZABBIX_USER=Admin
    - TEST_ZABBIX_PASSWORD=zabbix
    - TEST_ZABBIX_VERBOSE=1
  matrix:
    - ZABBIX_VERSION=3.0
    - ZABBIX_VERSION=3.4

before_install: sudo hostname travis && sudo -E ./setup.rb
